### ISSUE TITLE
JavaScript types

### ISSUE THREAD

**Issue by calvinmetcalf** [hypernumbers/LuvvieScript#2]
JavaScript doesn't have an int type, all numbers are doubles I don't believe that will effect the code, but will affect your documentation, same with strings which are utf16 in JavaScript not utf8.

**Comment by hypernumbers** [comment]
Good point - edited the README - so integers are now doubles - will just need to put a guard on sending messages from rErlang to LuvvieScript to impose a max size on Erlang bignums. Also added chars as an ascii type.

Also need to figure out if we can use native js string classes for LuvvieScript or transpose to a list of UFT16 codepoints like in Erlang. Might need to do some coercion on string types if we use them. (lets see how we go).

**Comment by calvinmetcalf** [comment]
for most purposes JavaScript strings act like they are ASCII strings e.g.`String.fromCharCode` takes ASCII code points as parameters and returns a string, to use that on an array you can use apply  `String.fromCharCode.apply(null,[97,115,102])` the main time the utf-16 stuff comes into play is when you do `'string'.length` because anything that is utf-16 will only be one char but count as 2 for length.
