### ISSUE TITLE
rebar make_luvv error

### ISSUE THREAD

**Issue by ztmr** [hypernumbers/LuvvieScript#6]
I am getting following errors when building:
  https://gist.github.com/ztmr/9009442

What am I doing wrong?

**Comment by hypernumbers** [comment]
> What am I doing wrong?

Trusting that I know what I am doing :(

I am working on getting test 1b working and I must have accidentally promoted it from my workspace after git mv'ing it from test/not_passing/src to test/passing/src

I have moved it back. Sorry.
